services:
  microservice:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    depends_on:
      - redis
      - elasticsearch
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: microservice.log
    networks:
      - database
      - elastic

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - database

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=es_password@123
    ports:
      - "9200:9200"
    networks:
      - database
      - elastic
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=es_password@123
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - database
      - elastic

  fluentd:
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
    depends_on:
      - kibana
    networks:
      - database
      - elastic

  admin:
    build:
      context: ./admin
    env_file:
      - ./admin/.env
    ports:
      - "8081:8081"
    depends_on:
      - microservice
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: admin.log
    networks:
      - database
      - elastic

networks:
  database:
    driver: bridge
  elastic:
    driver: bridge
